image: Ubuntu
init:
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true

build_script:
  - dotnet build  -c Release
  - dotnet test   -c Release --no-build
  - dotnet pack   -c Release --no-build --include-symbols -o ./deploy ./src/MyCalendar.fsproj

artifacts:
  - path: 'deploy/*.nupkg'
  - path: 'deploy/*.snupkg'